### ISSUE TITLE
RedBlackTree lessThan/lessThanEqual behavior

### ISSUE THREAD

**Issue by ptrfrncsmrph** [fp-ts/data#155]
### Current Behavior

Apologies if this is working as intended, but there aren’t currently any tests for `lessThan`/`lessThanEqual`, and the behavior seems unintuitive.

Given a `RedBlackTree` like
```ts
const tree = pipe(
  RedBlackTree.empty<number, string>(number.Order),
  RedBlackTree.insert(1, "a"),
  RedBlackTree.insert(0, "b"),
  RedBlackTree.insert(-1, "c"),
  RedBlackTree.insert(-2, "d"),
  RedBlackTree.insert(3, "e")
)
```

`lessThanEqual` produces the same result as `greaterThanEqual`

```ts
deepStrictEqual(
  Array.from(RedBlackTree.lessThanEqual(0.5)(tree)),
  Array.from(RedBlackTree.greaterThanEqual(0.5)(tree))
)
```

### Expected behavior

~I would expect `lessThanEqual` to produce a different result than `greaterThanEqual`.~ My expectation has been corrected here; they will produce the same result if passed a `key` that appears in the `RedBlackTree`, but they should not produce the same result otherwise.

### Suggested solution(s)

~I'm not entirely sure of the intended behavior, but~ currently `lessThanEqual` has the same implementation as `greaterThanEqual`, ~I'm guessing the intent was to reverse the `Direction` of the former?~ I have a PR here to modify the implementation to return an iterator from the greatest element that is less than or equal to the passed in `key`: https://github.com/fp-ts/data/pull/156

### Your environment

Latest `main` branch.

| Software    | Version(s) |
| ----------- | ---------- |
| @fp-ts/data |   0.0.27  |
| TypeScript  |  4.9.4  |

**Comment by ptrfrncsmrph** [comment]
@0x706b corrected my understanding: `lessThanEqual` should find the element in the tree less than or equal to the passed in `key`, and return an iterator from that element (not an iterator of elements less than or equal to the `key`, as I had assumed). The PR has been updated to just modify the `lessThanOrEqual` implementation.

**Comment by mikearnaldi** [comment]
Thanks  @ptrfrncsmrph !
