### ISSUE TITLE
Minimal set of methods in every module

### ISSUE THREAD

**Issue by mikearnaldi** [fp-ts/data#166]
Currently every module is purely pipeable, while this is the theoretical best for tree-shaking it leads to forcing pipe, and explicit imports, everywhere.

Let's see a few examples of that:

```ts
import * as Option from "@fp-ts/data/Option"

const logSome = <A>(o: O.Option<A>) => {
  if (O.isSome(o)) {
    console.log(o.value)
  }
}

const increment = <A>(o: O.Option<A>) => pipe(o, O.map(n => n + 1))
```

This leaves the user in a place where native types are pretty much always preferred, for example Array over Chunk, Nullable over Option, Map over HashMap, and so on and so forth.

When inspecting source code there are a number of functions that will end up in the bundle regardless, for example functions like `isSome / isNone / map` for `Option`, for such functions we are really not gaining anything by not putting them as methods too.

There may be an argument that methods cannot be minified but they can still be compressed, i.e. when using something like gzip that all the servers should support by default so the increase in minimum bundle size will be only apparent in uncompressed form.

Adding methods can also enable the addition of a `pipe` method that will provide the ability to do: `a.pipe(O.zip(b), O.zipFlatten(c))`.

Even adding a very minimum set of methods would smooth usage in the majority of the cases and would provide an API which is optimized for dot-completion.

Finally the only argument is serialization but:
1) it is domain for `/schema`
2) nobody who uses Option actually serializes it and deserializes it via JSON.parse/stringify, if they use direct JSON they will use nullable fields

This proposal follows the same reasoning behind method addition in ecosystem libraries such as `/optic`, we shouldn't make it more complex to use `@fp-ts/data` for no real benefit.

Note: Currently we have improper subtyping relationships, namely we have Either as a subtype of These, in languages like Haskell where those types originate every ADT is fully independent. While generally I don't like to draw too many parallelisms between languages I do think it would be a good idea not to force those artificial type-level relationships but opt in for explicit conversions (like these.toEither())

**Comment by patroza** [comment]
- minification: use the pipable version inside the method, or use function properties that are something like `unpipe(pipeable)` - perhaps even lazy?
- `pipe`: what about `apply`? Also, is there a way to define particular implementations as function instead, so they mimic tsplus `__call`?
- Serialisation: one can materialise `Option` back into a real Option object during Decode, like with `Date`.

**Comment by mikearnaldi** [comment]
- serialisation, Either and Option don't use symbols
- shaking, there's really no need, we use only pipeable in libs the methods will be for those who want to use them as a syntax sugar (based on the pipeable functions)
- apply would be a single argument but yes the name doesn't really matter

**Comment by adrian-gierakowski** [comment]
> Let's see a few examples of that:
> 
> ```ts
> import * as Option from "@fp-ts/data/Option"
> 
> const logSome = <A>(o: O.Option<A>) => {
>   if (O.isSome(o)) {
>     console.log(o.value)
>   }
> }
> 
> const increment = <A>(o: O.Option<A>) => pipe(o, O.map(n => n + 1))
> ```

Hmm, the first example doesn’t use pipe and the second should be able to simplify to:

```ts
const increment = O.map((n: number) => n + 1)
```

**Comment by mikearnaldi** [comment]
> > Let's see a few examples of that:
> > ```ts
> > import * as Option from "@fp-ts/data/Option"
> > 
> > const logSome = <A>(o: O.Option<A>) => {
> >   if (O.isSome(o)) {
> >     console.log(o.value)
> >   }
> > }
> > 
> > const increment = <A>(o: O.Option<A>) => pipe(o, O.map(n => n + 1))
> > ```
> 
> Hmm, the first example doesn’t use pipe and the second should be able to simplify to:
> 
> ```ts
> const increment = O.map((n: number) => n + 1)
> ```

They are minimized on purpose, the point is any time you need to do a single op unless you want to create a new function (like increment) you are forced into a pipe.

The `isSome` case shows the need for an explicit import, many times you get an option when using other api's and you just want to match on it / do something onSome / onNone

**Comment by evelant** [comment]
If the most common cases can be methods I think that would be very useful. After using tsplus I’ve found that I mostly use the methods for those very common cases with Option etc. Only downside I could see is potential confusion for newcomers when they access via `.` and only see a small subset of the API. It might not be obvious that those methods are only a subset and only there for convenience.

**Comment by mikearnaldi** [comment]
> If the most common cases can be methods I think that would be very useful. After using tsplus I’ve found that I mostly use the methods for those very common cases with Option etc (and discovering/remembering names of APIs but that’s not the scope here). Only downside I could see is potential confusion for newcomers when they access via `.` and only see a small subset of the API. It might not be obvious that those methods are only a subset and only there for convenience.

Could be well documented, also in line with native types like Array

**Comment by tim-smart** [comment]
I think I would prefer a consistent API design, rather than mixing and matching between pipeables and fluent. Keeps it predictable and less "messy".

**Comment by mikearnaldi** [comment]
Ok, I am never going to win this argument as it is too based on usage and doesn't have enough theoretical. We'll be trying to reduce friction by means of language service extensions such as https://github.com/Effect-TS/language-service

**Comment by matheusiacono** [comment]
> I still think this is a good idea. IMO it's usually good to favor dev experience over consistency/purity as long as the cost or complexity isn't high.

What is the meaning of dev experience in this context you are presenting?
IMO consistency reduces cognitive overload and that's an improvement on dev experience for me. But DX is a buzzword with multiple meanings and I'm curious to understand in which context you were writing about.

**Comment by evelant** [comment]
I was referring to this from the issue

> Even adding a very minimum set of methods would smooth usage in the majority of the cases and would provide an API which is optimized for dot-completion.

A minimal set of most commonly used functions added as methods IMO would make a lot of common cases more comfortable to write. For example instead of

```ts
import * as M from "@tsplus/stdlib/data/Maybe"


pipe(
   someOption
   M.getOrElse("foo"),
  ...
)
```

vs

```ts
someOption.getOrElse("foo")
```

Having very common functions as methods can make code more consice and avoid the need to add imports to many files where you're only using one of the most common functions.

It also eases the experience for newcomers since the operation they want will usually be available via `.` rather than requiring them to know ahead of time which function they need from which import. This has been covered thoroughly by mikearnaldi in [The Case for TS+](https://dev.to/effect-ts/the-case-for-ts-18b3).

IMO I don't see a downside to this proposal. If you want to have the consistency of always pipeing these common functions I don't think this proposal would prevent you from doing so.

**Comment by adrian-gierakowski** [comment]
> ```ts
> someOption.getOrElse("foo")
> ```

doesn't the following work? 

```ts
M.getOrElse("foo")(someOption)
``` 

I think you either want everything available as methods or nothing. How do you decide which methods should be available and which ones are not? Once you add some methods you'll get people asking for more. So maybe there could be 2 versions of each  package, one with no methods, and one with all methods? Like in [optics-ts](https://akheron.github.io/optics-ts/two-syntaxes/).

At the same time, maybe we should try to advance state of the art in LSP autocomplete, so that autocomplete could suggest available functions based on the type expected at current cursor location. If I write (`|` being my cursor): 

```ts
pipe(someOption, |
```

I would get all functions LSP is aware of which take `typeof someOption` as it's first argument

**Comment by mikearnaldi** [comment]
> > ```ts
> > someOption.getOrElse("foo")
> > ```
> 
> doesn't the following work?
> 
> ```ts
> M.getOrElse("foo")(someOption)
> ```
> 
> I still need to import `M\getOrElse`, but with LSP auto import this is supper low effort.
> 
> I think you either want everything available as methods or nothing. How do you decide which methods should be available and which ones are not? Once you add some methods you'll get people asking for more. So maybe there could be 2 versions of each package, one with no methods, and one with all methods? Like in [optics-ts](https://akheron.github.io/optics-ts/two-syntaxes/).
> 
> At the same time, maybe we should try to advance state of the art in LSP autocomplete, so that autocomplete could suggest available functions based on the type expected at current cursor location. If I write (`|` being my cursor):
> 
> ```ts
> pipe(someOption, |
> ```
> 
> I would get all functions LSP is aware of which take `typeof someOption` as it's first argument

two versions of the same package is simply an insanity, and as the proposal states tree-shaking is very important and we wouldn't be acceptable with large set of methods (note that something like effect/io has 1000s of functions per module).

the following doesn't generally work:

```ts
M.getOrElse("foo")(someOption)
```

TS will infer the type `left-to-right` and in any case the type of the left depends on the right it will give inference issues making something like `map(f)(option)` completely impossible to use.

Auto-completion when you already wrote pipe isn't a big deal, the problem really is forcing pipe for very common and short things but we may be able to improve the LSP thanks to the work in TS+ and to the language extension that @mattiamanzati is working on.

Namely in TS+ we have the ability to write `o.map(f)` when `map` is recognized as an extension method that is translated to `pipe(o, O.map(f))` it would be a matter to allow that via either a language service extension or a vscode plugin that when you write `o.map` auto-completes to `pipe(o, O.map(***))`
