### ISSUE TITLE
Port Data Structures and TypeClasses from Core

### ISSUE THREAD

**Issue by mikearnaldi** [fp-ts/data#45]
Following shrinkage of `core` scope the following modules needs porting:

- [ ] ReadonyArray
  - [x] tests (@IMax153 #50)
  - [ ] `Alt` & `Category`
- [ ] NonEmptyReadonlyArray 
  - [x] tests (@IMax153 #58)
  - [ ] `Alt` & `Category`
- [ ] Option 
  - [x] tests (@IMax153 #46)
  - [ ] `Alt` & `Category`
- [ ] Result 
  - [x] tests (@IMax153 #46)
  - [ ] `Alt` & `Category` 
- [x] Compactable (@IMax153 #46)
- [x] Filterable (@IMax153 #51)
- [x] TraversableFilterable (@IMax153 #52)
- [x] Const (@gcanti #55)
- [x] Identity (@gcanti #53)
- [ ] These (@enricopolanski WIP)

Note: this issue is in WIP
Note: I've ported pretty modules dumbly, i.e. all the new Semigroupal/Monoidal instances should be optimized

**Comment by mikearnaldi** [comment]
My bad FromOption and FromResult have been added by mistake, there is a pass of renaming needed we still use old naming of things like Applicative around the code and should follow the new naming convention to Monoidal/Semigroupal/etc

**Comment by mikearnaldi** [comment]
Actually I retract there are things like `liftPredicate` implemented using those - cc @gcanti

**Comment by gcanti** [comment]
Some observations after upgrading to 0.0.6 and trying to achieve 100% coverage

### `NonEmptyReadonlyArray` module

now there are 

- `product` (ex `crossWith`)
- `productMany` (ex `crossMany`)
- `productAll` (ex `crossAll`)

but also

- `zipMany`
- `zipAll`

are we interested in `zipMany`, `zipAll` or they can be removed?
In case we want to keep them even if they are not part of any instance, I think they need some tests for the corner cases (empty array as argument)

### `String` module

Last functions that need tests

- `linesIterator`
- `stripMarginWith`
- `isLineBreak2`

I wasn't 100% sure what's the intended behaviour so I didn't add any test

### `List` module

The `sortWith` function should be renamed to `sort` I guess (AFAIK the convention is using `with` when a mapping is involved)

**Comment by mikearnaldi** [comment]
outdated
