### ISSUE TITLE
Fix examples in every module

### ISSUE THREAD

**Issue by mikearnaldi** [fp-ts/data#64]
When porting we changed the module structure and some functions behave differently (like `uniq` non requiring `Eq<A>`) this made all examples no longer compiling, we should go through each module and fix the examples and add examples where missing.

The process should be:
1: change the jsdoc tag `@exampleTodo` to `@example`
2: fix the example code
3: run `pnpm run docs` and make sure it is compiling

Modules:
- [x] Boolean
- [ ] Chunk
- [ ] Const
- [ ] Context
- [ ] Differ & Patches
- [ ] Duration
- [ ] Endomorphism
- [ ] Equal
- [x] Function
- [ ] HashMap
- [ ] HashSet
- [ ] Identity
- [ ] List
- [ ] MutableHashMap
- [ ] MutableHashSet
- [ ] MutableList
- [ ] MutableListBuilder
- [ ] MutableQueue
- [ ] MutableRef
- [x] NonEmptyReadonlyArray
- [x] Number
- [x] Option
- [ ] Predicate
- [ ] Queue
- [ ] ReadonlyArray
- [ ] RedBlackTree
- [ ] Refinement
- [x] Result
- [x] Either
- [ ] SafeEval
- [ ] SortedMap
- [ ] SortedSet
- [x] String
- [ ] Compactable
- [ ] Filterable
- [ ] TraversableFilterable
- [ ] WeakIterableMap

**Comment by tatchi** [comment]
> 3: run pnpm run docs and make sure it is compiling

I think the correct command is `pnpm run gen-docs` https://github.com/fp-ts/data/blob/main/package.json#L43

**Comment by mikearnaldi** [comment]
outdated
